[package]
name = "raytracer-1weekend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.27.0"
indicatif = "0.17.8"
itertools = "0.12.1"
rand = "0.8.5"

